// Generated by dojo-bindgen on Thu, 24 Oct 2024 15:26:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace overdrive {
    // Model definition for `overdrive::models::player_models::PlayerAccount` model
    public class PlayerAccount : ModelInstance {
        [ModelField("player_address")]
        public FieldElement player_address;

        [ModelField("username")]
        public FieldElement username;

        [ModelField("games_played")]
        public uint games_played;

        [ModelField("games_won")]
        public uint games_won;

        [ModelField("creation_time")]
        public ulong creation_time;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        