// Generated by dojo-bindgen on Thu, 24 Oct 2024 15:26:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace overdrive {
    // Model definition for `overdrive::models::player_models::PlayerState` model
    public class PlayerState : ModelInstance {
        [ModelField("player_address")]
        public FieldElement player_address;

        [ModelField("is_bot")]
        public bool is_bot;

        [ModelField("game_id")]
        public uint game_id;

        [ModelField("score")]
        public ushort score;

        [ModelField("shield")]
        public byte shield;

        [ModelField("energy")]
        public byte energy;

        [ModelField("last_action_time")]
        public ulong last_action_time;

        [ModelField("playing")]
        public bool playing;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        