// Generated by dojo-bindgen on Thu, 24 Oct 2024 15:26:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit {}
}

// Type definition for `core::byte_array::ByteArray` struct
[Serializable]
public struct ByteArray {
    public string[] data;
    public FieldElement pending_word;
    public uint pending_word_len;
}

// Type definition for `dojo::model::layout::FieldLayout` struct
[Serializable]
public struct FieldLayout {
    public FieldElement selector;
    public Layout layout;
}

// Type definition for `overdrive::models::game_models::GameMode` enum
public abstract record GameMode() : Enum {
    public record SinglePlayer() : GameMode;
    public record MultiPlayer() : GameMode;
}

// Type definition for `overdrive::models::game_models::GameStatus` enum
public abstract record GameStatus() : Enum {
    public record Ongoing() : GameStatus;
    public record Ended() : GameStatus;
}

// Type definition for `dojo::model::layout::Layout` enum
public abstract record Layout() : Enum {
    public record Fixed(byte[] value) : Layout;
    public record Struct(FieldLayout[] value) : Layout;
    public record Tuple(Layout[] value) : Layout;
    public record Array(Layout[] value) : Layout;
    public record ByteArray() : Layout;
    public record Enum(FieldLayout[] value) : Layout;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


namespace overdrive {
    // Model definition for `overdrive::models::game_models::GameState` model
    public class GameState : ModelInstance {
        [ModelField("id")]
        public uint id;

        [ModelField("player_1")]
        public FieldElement player_1;

        [ModelField("player_2")]
        public FieldElement player_2;

        [ModelField("status")]
        public GameStatus status;

        [ModelField("mode")]
        public GameMode mode;

        [ModelField("winner_address")]
        public FieldElement winner_address;

        [ModelField("result")]
        public (byte, byte) result;

        [ModelField("start_time")]
        public ulong start_time;

        [ModelField("end_time")]
        public ulong end_time;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        