// Generated by dojo-bindgen on Thu, 24 Oct 2024 15:26:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `overdrive::models::player_models::Cipher` struct
[Serializable]
public struct Cipher {
    public CipherTypes cipher_type;
    public byte cipher_value;
}

// Type definition for `overdrive::models::player_models::CipherTypes` enum
public abstract record CipherTypes() : Enum {
    public record Advance() : CipherTypes;
    public record Attack() : CipherTypes;
    public record Shield() : CipherTypes;
    public record Energy() : CipherTypes;
    public record Unknown() : CipherTypes;
}


namespace overdrive {
    // Model definition for `overdrive::models::player_models::PlayerCiphers` model
    public class PlayerCiphers : ModelInstance {
        [ModelField("player_address")]
        public FieldElement player_address;

        [ModelField("is_bot")]
        public bool is_bot;

        [ModelField("hack_cipher_1")]
        public Cipher hack_cipher_1;

        [ModelField("hack_cipher_2")]
        public Cipher hack_cipher_2;

        [ModelField("hack_cipher_3")]
        public Cipher hack_cipher_3;

        [ModelField("deck_cipher_1")]
        public Cipher deck_cipher_1;

        [ModelField("deck_cipher_2")]
        public Cipher deck_cipher_2;

        [ModelField("deck_cipher_3")]
        public Cipher deck_cipher_3;

        [ModelField("deck_cipher_4")]
        public Cipher deck_cipher_4;

        [ModelField("deck_cipher_5")]
        public Cipher deck_cipher_5;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        