// Generated by dojo-bindgen on Thu, 24 Oct 2024 15:26:40 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace overdrive {
    // Model definition for `overdrive::models::player_models::PlayerAssets` model
    public class PlayerAssets : ModelInstance {
        [ModelField("player_address")]
        public FieldElement player_address;

        [ModelField("cars")]
        public FieldElement cars;

        [ModelField("profile_icons")]
        public FieldElement profile_icons;

        [ModelField("garage_environments")]
        public FieldElement garage_environments;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        